version: "3"
services: 
    telegraf:
        image: telegraf
        container_name: dc-telegraf
        ports:
            - "8125:8125"
            - "8092:8092"
            - "8094:8094"
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
